# Generated by Django 3.2.12 on 2022-04-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_proposal_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proposal',
        ),
    ]
