# Generated by Django 3.2.11 on 2022-02-06 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary', models.BinaryField(blank=True, null=True)),
                ('bool', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('str', models.TextField(max_length=129)),
                ('int', models.IntegerField(blank=True, null=True)),
                ('float', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FKModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreignkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fkname', to='funwithmodels.commondatatypes')),
            ],
        ),
    ]
