# Generated by Django 3.2.12 on 2022-04-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('date', models.DateField(auto_now=True)),
                ('projectAuthor', models.CharField(max_length=128)),
                ('projectTitle', models.CharField(max_length=100, verbose_name='Project Title')),
                ('projectDescription', models.CharField(max_length=256, verbose_name='Project Description')),
                ('proposalFile', models.FileField(null=True, upload_to='projects/proposals', verbose_name='Proposal')),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=256)),
                ('file', models.FileField(upload_to='projects/')),
                ('type', models.IntegerField()),
                ('uploadDate', models.DateTimeField(auto_now=True)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
    ]
