# Generated by Django 3.2.12 on 2022-04-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='type',
            field=models.IntegerField(blank=True),
        ),
    ]
