# Generated by Django 3.2.12 on 2022-04-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dataFile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='resultFile',
        ),
    ]
