# Generated by Django 3.2.12 on 2022-04-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220411_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
