# Generated by Django 3.2.12 on 2022-04-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220429_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfile',
            old_name='dataFile',
            new_name='file',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='type',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='ResultFile',
        ),
    ]
