# Generated by Django 3.2.12 on 2022-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_projectfile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='type',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
