# Generated by Django 3.2.12 on 2022-04-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_proposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dataFiles',
            new_name='proposalFile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='resultFiles',
        ),
    ]
