# Generated by Django 3.2.12 on 2022-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220415_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectDescription',
            field=models.CharField(default='tmp', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='proposalFile',
            field=models.FileField(upload_to='projects/proposals'),
        ),
    ]
