# Generated by Django 3.2.12 on 2022-04-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220415_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(default='cody.conner@western.edu', max_length=256),
            preserve_default=False,
        ),
    ]
